### PR TITLE
Added kubernetes yaml files

### PR DESCRIPTION
**Pull request by kersten**
A first set of yaml files for kubernetes.

### CODE REVIEW

**Comment by monotek** [comment]
Question: why do you use Zammad nginx container?

Imho the kubernetes ingress controller could do the work too.

**Comment by kersten** [comment]
I just copied the docker setup over to kubernetes.

Is the kubernetes Ingress able to mount the pvc and use a custom config with wss?

Another question would be, eg: Is the tectonic ingress able to do that too.

**Comment by kersten** [comment]
Another thing: I don't know the zammad core, would it be possible to use nginx websocket upstream functionality instead of the custom wss port?

**Comment by monotek** [comment]
I'm not sure that all ingress controllers support it but at least nginx & traefik ingress controlles can do it: 

Nginx example: https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/websocket/README.md

**Comment by kersten** [comment]
Ok, I will have a look at it, but that's stuff for tomorrow or so. I have to see.

**Comment by monotek** [comment]
No hurry!
Thanks for your work :-)

**Comment by kersten** [comment]
This one is now working as expected. Let me know if you have another wish :)

**Comment by kersten** [comment]
Maybe I could add a couple more Readme.md stuff.

At least tell people that the need ReadWriteMany persistent volumes. This can be delivered from glusterfs or storageos.

**Comment by monotek** [comment]
Google cloud test failed :-( 

Had to remove the s3 & cronjob yml files to get through "kubectl apply -f ." but containers wont start because of errors like:

* warning PersistentVolumeClaim is not bound: "zammad-home" (repeated 3 times) default-scheduler
* warning Failed to provision volume with StorageClass "standard": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce ReadOnlyMany] are supported

I'll try with minkube later.

**Comment by monotek** [comment]
It also did not work out of the box on minikube. 

GCE was not so much of a suprise. Maybe it works by adding some special storage container (nfs, or glusterfs). But i don't have enough time at the moment to try it out.

Did you tried it somewhere else as in your environment? At least on Minikube it should work out of the box, to be able to test it.

**Comment by kersten** [comment]
Hi,

this is correct. For Zammad you will need ReadWriteMany disks. This is possible using eg GlusterFs or storageos. But that setup would be overkill to list here and hardly to maintain. As I said, maybe the documentation needs to be a bit more clear.

I never tried minikube, so I don't know if we could get this working out of the box.

**Comment by monotek** [comment]
As minikube is the official kubernetes testing environment we should try to get it work there. This should also be generic enough to use it as a starting point to get it work in other environments.

**Comment by monotek** [comment]
Update....
Got it running on Minikube, by starting with a fresh installation. Seems my Minikube installation was to old or fucked up in some way. I'll push soon with some changes...

**Comment by monotek** [comment]
After a while the websocket and scheduler containers crashed. 

```
PersistentVolumeClaim is not bound: "zammad-home"
Back-off restarting failed container
Error syncing pod
```

Pod log of scheduler and websocket server look like:

```
scheduler can access raillsserver now...
Bundler::GemNotFound: Could not find rake-12.0.0 in any of the sources
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
  /usr/local/lib/ruby/gems/2.4.0/gems/bunhungen für dieses Kino möglichdler-1.15.4/lib/bundler.rb:101:in `setup'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
  /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
bundler: failed to load command: script/scheduler.rb (script/scheduler.rb)
```

I guess its still a problem that the all containers try to write to zammads tmp dir.

I tend to create kubernetes containers which use nfs or glusterfs to share a network directory.

**Comment by kersten** [comment]
Hi, yes this sounds like a volume problem. I use glusterfs as ReadWriteMany volumes. I had that error too, restarting railsserver helped. But that would not be the solution.

We will get this working soon, I hope :)

**Comment by kersten** [comment]
The removal of S3 is correct I think. It's something like glusterfs that should not be handled here. I think its not working because you didn't pass correct config values.

**Comment by monotek** [comment]
We'll evaluate to use memcached like described in: https://github.com/zammad/zammad/issues/1601

**Comment by Geo719** [comment]
Hi,
I pulled the docker-compose version of Zammad. Next I tried running kompose convert / kompose up after altering the docker-compose.yml version from 3.3 to 3.

The system starts up but there are problems:
1. After kompose up: FATA Error while deploying application: persistentvolumeclaims "data-zammad" already exists 
Along with this the zammad-nginx pod gives following errors:
```
PersistentVolumeClaim is not bound: "data-zammad"
Back-off restarting failed container
Error syncing pod 
```
-----

2. zammad-nginx exists with error because of:
`nginx: [emerg] host not found in upstream "zammad-railsserver:3000" in /etc/nginx/conf.d/zammad.conf:8`

any clues?

**Comment by monotek** [comment]
Did you even read whats written here?
It does not work, without shared storage.
Thats teh reason its not merged.

**Comment by Geo719** [comment]
Yes, I did read - maybe I did not understand.
So minikube does not "support" ReadWriteMany. 
Would it be an option to use NFS?
`minikube start --feature-gates=DynamicVolumeProvisioning=false`
and then hook on a NFS? 

Beside, why using docker-compose v3.3? There are no v3.3 specific rules?!

**Comment by Geo719** [comment]
monotek, I had not seen the issue #1601
Thanks for the hint

**Comment by monotek** [comment]
Yes, NFS, Glusterfs or whatever network filesystem would work. Unfortunately it's kind of overhead to add this to Zammad, as additional containers (storage server) and changes to existing ones (storage clients) would be needed.

That's the reason we thinking about to implement memcached instead, as parts of Zammad (cache) would already support it.

Unfortunately we don't have a schedule for that at the moment. So voting for the linked issue could help speed up things a bit ;-)

Can't remember the reason for compose v3.3. Maybe there is none.

**Comment by Geo719** [comment]
OK, I think I got it and already voted :)

**Comment by monotek** [comment]
@kersten 

Another question: why did you choosed to use stateful sets for all containers?

**Comment by monotek** [comment]
I just merged your changes.Many thanks again :-)
Also added a NFS server to fix the volume issues.

**Pull request closed without merging**
