### PR TITLE
Release Update 3.6.

### PR DESCRIPTION
**Pull request by thorsteneckel**

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hi @monotek - would you mind doing the review?

**Review by monotek — CHANGES_REQUESTED** [review]
Please add 3.6.0-1 in https://github.com/zammad/zammad-docker-compose/blob/master/.env#L6 too :)

**Comment by thorsteneckel** [comment]
> Please add 3.6.0-1 in https://github.com/zammad/zammad-docker-compose/blob/master/.env#L6 too :)

Thanks! I will. Just for clarification: The [previous process](https://github.com/zammad/zammad-docker-compose/pull/162#discussion_r440695986) of waiting for the first build is obsolete then?

**Comment by monotek** [comment]
It's already there ;-)

https://hub.docker.com/repository/docker/zammad/zammad-docker-compose/tags?page=1

**Comment by thorsteneckel** [comment]
Good to know 💡 Thanks! Added 👍

**Review by monotek — APPROVED** [review]

**Pull request merged**
