### PR TITLE
update zammad & components 

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <andre.bauer@staffbase.com>

* Zammad update to 5.2.3-32
* Elasticsearch was updated from 7.17.3 to 8.5.0 using bitnami image
  * custom image build removed as ingest plugin is part of 8.x image
  * Deleting the index and reindex everything might be needed
* PostgreSql was updated from 9.6.24 to 15.0.0
  * backup / restore ins needed to update
  * custom build image was removed

### CODE REVIEW

**Comment by waja** [comment]
Are there plans to support/move over to opensearch?

**Comment by MrGeneration** [comment]
I would apprieciate it if the backup and restore process could actually use the original contrib version instead of an own version.
Not all configuration types are supported and this also may lead to serious compatibility issues in my opinion.

@waja Sorry but that really doesn't belong into an PR but an issue. While Zammad technically supports opensearch, we still do recommend Elasticsearch.

**Comment by monotek** [comment]
@MrGeneration 
feel free to update the original script to work in a container environment.

@waja 
i've never tried opensearch so from my point of view it seems a lot of testing is needed and i don't want to invest the time.

**Comment by MrGeneration** [comment]
> feel free to update the original script to work in a container environment.

@monotek did you actually try the current version or have a look at it? I believe that it should work out of the box.
I'll maybe have a look way after my vacation. Sorry for stepping in and mentioning an issue.

**Comment by monotek** [comment]
> @monotek did you actually try the current version or have a look at it?

not recently as it's not in the scope of my changes.
i just think i've created the other version for a reason.

**Comment by waja** [comment]
This postgresql migration looks kinda PITA. How about something like https://hub.docker.com/r/tianon/postgres-upgrade and using the tag `9.6-to-15`?

**Comment by monotek** [comment]
@waja 

Would you mind to test it and create a PR which updates the instructions?

**Pull request merged**
