### PR TITLE
Added zpm addon scripts deployment

### PR DESCRIPTION
**Pull request by arnaudveron**
* once a zpm package is installed through auto_install, it populates ${ZAMMAD_DIR}/db/addon/<package> with rb scripts
* this commit now triggers package migration, and rebuilds assets

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Thanks @arnaudveron ! Source: https://community.zammad.org/t/docker-compose-implementation-zpm-auto-install/7465/2

@mgruner / @monotek would you mind reviewing this?

**Comment by monotek** [comment]
Im a bit unsure about this one. 
Normally installing packages into a container is wrong, as containers should be immutable.
The right way to go would be to create a new container, which already has the package included.
At least in this case the package is not downloaded somewhere but put in via volume mount, so this would not crash on a failed download. 

If we want to keep the featureset of the docker-compose and the helm install the same, i would rather not implement it here, as in k8s there is no easy way to mount data in.

**Review by monotek — COMMENTED** [review]
Im a bit unsure about this one.
Normally installing packages into a container is wrong, as containers should be immutable.
The right way to go would be to create a new container, which already has the package included.
At least in this case the package is not downloaded somewhere but put in via volume mount, so this would not crash on a failed download.

If we want to keep the featureset of the docker-compose and the helm install the same, i would rather not implement it here, as in k8s there is no easy way to mount data in.

**Comment by arnaudveron** [comment]
In my use case, the package is not installed in the container, but by the container, because of container volumes used for /auto_install, and /opt/zammad.

The zpm package is not downloaded but just bind mounted into the container, from a configmap running into the cluster, so this can't fail as as soon as the config map exist.

My (opensvc cluster) container config snippet is as below:

```
[container#1]
type = oci
image = {env.zamimage}
netns = container#0
rm = true
volume_mounts = zammad-data/:/opt/zammad {name}-custom/:/custom {name}-zpm/:/opt/zammad/auto_install
secrets_environment = POSTGRESQL_USER=postgres/pguser POSTGRESQL_PASS=postgres/pgpassword
configs_environment = env/*
start_timeout = 600s
shared = true
detach = false
run_command = zammad-init
```

So I believe that using auto_install feature available in the zammad container is a valid option, which is more dynamic than building a new container image each time a custom zpm package requires a change.

**Comment by monotek** [comment]
There is no way to use this kind of mount in k8s therefore closed....

**Comment by arnaudveron** [comment]
Hi

I do not share your point of view about k8s because I believe it supports volume mounts from (at least)
* configmap volume projection https://kubernetes.io/docs/tasks/configure-pod-container/configure-projected-volume-storage/
* persistent volumes https://kubernetes.io/docs/concepts/storage/volumes/

Lets assume that I'm wrong and k8s does not support volume mount, k8s is not the only container orchestrator to operate containers, so why levelling down zammad container capabilities to what k8s supports or not ?

Of course, I can understand your choice considering that k8s is often used, but I think it is limiting the zammad deployment on heterogeneous container orchestrators, and it is really sad.

This proposed change just add a kind of install hook, and it does not change the initial container behavior if nothing is mounted under auto_install, so it not very intrusive, that's why I would be happy that your reconsider your decision about the PR.

With respect, best regards.

**Comment by monotek** [comment]
Configmaps and secrets have a 1mb limit (from etcd) and using a predefined volume with data in an k8s environment wouldbe something very unusual.

**Pull request closed without merging**
