### PR TITLE
update image to 3.5.0-20

### PR DESCRIPTION
**Pull request by rosscdh**
Upgraded to feature/3.6-upgrade

### CODE REVIEW

**Comment by MrGeneration** [comment]
Woah stop.
Zamnmad 3.6.x is no stable built!

**Comment by monotek** [comment]
Right. Stable images can be found here: 
https://hub.docker.com/repository/docker/zammad/zammad-docker-compose/tags?page=1
So you could update to 3.5.20

**Comment by rosscdh** [comment]
May I ask when these images will become available?

**Comment by MrGeneration** [comment]
Which images...?

**Comment by rosscdh** [comment]
zammad/docker-compose:zammad-xxx
zammad/docker-compose:elasticsearch-xxx
zammad/docker-postgres-xxx
zammad/docker-compose:-xxx

**Comment by MrGeneration** [comment]
```
- zammad/zammad-docker-compose:zammad-3.5.0-20
- zammad/zammad-docker-compose:zammad-postgresql-3.5.0-20
- zammad/zammad-docker-compose:zammad-elasticsearch-3.5.0-20
```

Already are available...?
Newer versions are pushed as soon as they're updates on stable within 2 hours.

**Comment by rosscdh** [comment]
Pretty much what i expected (thanks for confirming) however when i tested
there were none available

and still not https://hub.docker.com/r/zammad/zammad-docker-compose/tags

perhaps affected by the recent docker hub limits?

**Comment by MrGeneration** [comment]
Use the search function of the hub. The image tag is available.

**Comment by rosscdh** [comment]
ahI.. I am actually after 3.6 not 3.5? as there are trigger changes there that I need and I understood it was recently released

https://github.com/zammad/zammad/releases/tag/3.6.0

**Comment by MrGeneration** [comment]
Okay, again:
Zammad 3.6 currently **is not stable** but develop.

3.6 tag within the main repo is the preparation and will transition to stable if the official release is there.
Stable releases are listed here: https://zammad.com/news/category:release

**Pull request merged**
