### PR TITLE
Added postgres env data

### LINKED ISSUE #355: Password authentication failed for user "zammad" after upgrading to Zammad 6.x
# Description

After upgrading to Zammad 6.x using the Docker configuration from this repository, the instance won't start up anymore, because the init container fails to connect to postgres.

We have specified a custom `POSTGRES_PASS` in `.env`, which previously worked. I noticed that in the new release, the `zammad-init` container doesn't have the `POSTGRESQL_USER` and `POSTGRESQL_PASS` variables set. Do I have to provide the password to the init container differently?

# Infos

* Docker version: Docker version 24.0.2, build cb74dfc
* Docker-compose version: Docker Compose version v2.18.1
* Operating system (Docker host): Debian 10.13

# Expected behavior

* When starting Zammad using `docker compose up`, Zammad starts up.

# Actual behavior

Zammad does not start up, but the init container does instead fail with the message:

```
zammad-zammad-init-1           | PG::ConnectionBad: FATAL:  password authentication failed for user "zammad"
zammad-zammad-init-1           | /usr/local/bundle/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
zammad-zammad-init-1           | /usr/local/bundle/gems/pg-1.2.3/lib/pg.rb:58:in `new'
zammad-zammad-init-1           | /usr/local/bundle/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql_adapter.rb:78:in `new_client'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_handling.rb:283:in `connection'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/relation/delegation.rb:93:in `connection'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/relation/query_methods.rb:1396:in `preprocess_order_args'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/relation/query_methods.rb:383:in `reorder!'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/relation/query_methods.rb:378:in `reorder'
zammad-zammad-init-1           | /usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/querying.rb:22:in `reorder'
zammad-zammad-init-1           | /opt/zammad/app/models/setting.rb:105:in `load'
zammad-zammad-init-1           | /opt/zammad/app/models/setting.rb:56:in `get'
```

# Steps to reproduce

* Have a Zammad instance configured with a password for PostgreSQL that is not `zammad`
* Upgrade to the latest version of `zammad-docker-compose`
* Start Zammad.

### LINKED ISSUE #356: How to update zammad 5.4 to 6 ?
* Docker version:  20.10.21
* Docker-compose version:  1.25.0
* Operating system (Docker host): Ubuntu 20.04.6 LTS 

How to update zammad 5.4 to 6 ? 

Where can I see instructions? Thank you.

### PR DESCRIPTION
**Pull request by Finnlife**
Added missing Postgresql connection data in docker-compose.yml

Resolves #356, Resolves #355

### CODE REVIEW

**Comment by ggruening** [comment]
Maybe we're missing a few other environment-variables, too? See #358 and the answers. There seems to be a problem with elasticsearch and/or rake.

**Comment by Finnlife** [comment]
@ggruening Maybe there are.
But what did change that causes this?
When we know that, we will be able to find all missing env variables.

@t3easy I tried to add the DB Name as an Env var, but that didn't work for me.
I'm currently not able to test this because I only have access to a prod Instance of zammad.
I might be able to test this in a couple of days.
I just wanted to fix this issue for all of the users.

**Comment by t3easy** [comment]
I just added this vars a few commits back but they are gone now with the commit for v6 without a comprehensible reason.

This commit for v6 seems very breaking to me.

**Comment by Finnlife** [comment]
Thank you, @t3easy, for your feedback.
I added the DB-Name in the envs.
I know that I added the DB Envs as Containers that did not have them in versions prior to 6, but I think I got problems at some containers because of missing DB-Envs.
Maybe there was a Change in v6.

I will look into this after this is being fixed / merged.

**Comment by AnXh3L0** [comment]
@Finnlife I am trying to setup Zammad via Docker, and I tried to add the vars, just like you did, but I still get the postgres auth error. Do you know if there's anything else that has to be changed in order for this to work?

**Comment by kamilkobak** [comment]
You probably need to change the authentication in postgres which is in the file `pg_hba.conf `
This file is in docker postgres volume: `postgresql-data`  
In my case:
`vim /var/lib/docker/volumes/zammad-docker-compose_postgresql-data/_data/pg_hba.conf `

change last line to:
`host  all  all  172.0.0.1/8  trust`
(Include your docker network address here)

**Comment by Finnlife** [comment]
@AnXh3L0 yeah I had this issue too.
Check if you 100% wrote the vars correct.
Its `POSTGRESQL_DB` not `POSTGRES_DB` as in the Postgres Container env.
If this doesn't help, send me your full docker-compose file

**Comment by fleverest** [comment]
This issue is not specific to this repository. As such, I have created [PR 4735](https://github.com/zammad/zammad/pull/4735) on the `zammad/zammad` repo.

**Comment by ggruening** [comment]
@fleverest  Thanks for finding that out! 😃 Let's hope your PR gets merged quickly. 😅

**Comment by t3easy** [comment]
> This issue is not specific to this repository. As such, I have created [PR 4735](https://github.com/zammad/zammad/pull/4735) on the `zammad/zammad` repo.

I would like to see them set in docker-compose.yml + .env because services like the backup override the entrypoint. And it is much clearer how to adjust them.

**Comment by fleverest** [comment]
> > This issue is not specific to this repository. As such, I have created [PR 4735](https://github.com/zammad/zammad/pull/4735) on the `zammad/zammad` repo.
> 
> I would like to see them set in docker-compose.yml + .env because services like the backup override the entrypoint. And it is much clearer how to adjust them.

You're right, I misunderstood the main issue for this PR

**Comment by thmo** [comment]
Please add `POSTGRESQL_HOST` in addition. It might not be absolutely necessary in the case of (vanilla) docker-compose as the db container is automatically named `zammad-postgres`, similar to what the entrypoint script expects. However, in some cases, where the `docker-compose.yml` only serves as a blueprint (in my case, a script setting up a podman pod), the hostname might in fact be different. Adding `POSTGRESQL_HOST` would makes things more explicit and thus clearer, especially as `POSTGRESQL_HOST` is mentioned in `.env`.

As a side note, speaking of `.env`, it would probably be easier to simply use `env_file` with `.env` instead of listing variables individually.

**Comment by pgassmann** [comment]
with the most recent update, also zammad-nginx requires the postgres credentials https://github.com/zammad/zammad/pull/4684

**Comment by mgruner** [comment]
@Finnlife please see #366 for a more complete version and let me know if this works for you. Thanks!

**Comment by mgruner** [comment]
Actually everyone is invited to test and give feedback, of course!

**Pull request closed without merging**
