### PR TITLE
Update to Zammad 6.4, and perform major dependency updates including postgres 17.

### PR DESCRIPTION
**Pull request by mgruner**
This includes a major update for the postgres dependency from 15 to 17, which requires manual action to upgrade the postgresql cluster data to the new version.

### CODE REVIEW

**Review by monotek — APPROVED** [review]
i guess link to upgrading docs will be added in the relase notes?

**Comment by mgruner** [comment]
Yes: https://www.postgresql.org/docs/17/upgrading.html, I will add it to the tag description.

**Comment by mgruner** [comment]
@waja thanks for the tip, added to https://github.com/zammad/zammad-docker-compose/releases/tag/v13.0.0.

**Comment by terdinatore** [comment]
@mgruner IMPORTANT: Using the docker method suggested by @waja breaks prevents the database from starting because it's using the 17:bookworm image to upgrade instead of 17:alpine that is used in zammad-compose! 

I got an error: `database "zammad_production" has no actual collation version, but a version was recorded` that could only be fixed by moving to 17:bookworm image in the zammad compose file. (See this: https://stackoverflow.com/a/78572273)

**Comment by tgoti** [comment]
Just as an idea, maybe this is a way easier solution to do the upgrade. Since I was searching for an easy way.
https://github.com/pgautoupgrade/docker-pgautoupgrade
It means to just change the image for the upgrade and switch it back afterwards. Maybe with the environment  PGAUTO_ONESHOT: yes

**Comment by hubertnubert** [comment]
> Just as an idea, maybe this is a way easier solution to do the upgrade. Since I was searching for an easy way. https://github.com/pgautoupgrade/docker-pgautoupgrade It means to just change the image for the upgrade and switch it back afterwards. Maybe with the environment PGAUTO_ONESHOT: yes


This is really the easiest solution. 
Just stop the stack and enter (change the variables and your path to the db):

`docker run --name pgauto -it \
	--mount type=bind,source=/var/lib/docker/volumes/zammad_postgresql-data/_data,target=/var/lib/postgresql/data \
	-e POSTGRES_DB=zammad_production \
	-e POSTGRES_USER=zammad \
	-e POSTGRES_PASSWORD=zammad \
	-e PGAUTO_ONESHOT=yes \
	pgautoupgrade/pgautoupgrade:17-alpine`

Start the stack. 
Finished.

**Pull request merged**
