### PR TITLE
Support other databases and no elasticsearch

### PR DESCRIPTION
**Pull request by pschichtel**
I'm currently trying to migrate a rather old instance of Zammad to a Docker swarm. The instance is using MySQL and no Elasticsearch. This docker-compose setup currently does not support this setup, but I think it is fairly simple to support. The suggested changes have been done in the browser and are not tested yet, I'm just interested in feedback for the moment.

Would this be of interest?

### CODE REVIEW

**Comment by monotek** [comment]
I had mysql support in mind several times but decided against it as i don't want to maintain a second db option.

By the way its not adviced to run zammad without elasticsearch so i'd rather like not to add this option.

**Comment by pschichtel** [comment]
Would you accept just the database support change? It's kind of unfortunate that you support and document MySQL, but do not support it with your Docker images. The way the image is done I also can't just use a config object to overwrite the config. That leaves me with no other option but to fork this project.

About ES: I've seen the notes in the documentation and I've decided that the limitations that this will cause are fine for me. Why hardcode the ES requirement into the entrypoint? The current instance sees very little use and there is no need for a lot of searching.

**Comment by MrGeneration** [comment]
Just a small side note from me to the database topic:
I can understand André perfectly if he doesn't want to support further databases.
While we support MySQL/MariaDB installations, we also encourage users to not use it, as we had a a lot better experience and less issues with postgresql. Some issues are MySQL related. 

That remark can be found here:
https://docs.zammad.org/en/latest/prerequisites/software.html#database-server

While I can understand you and your need for MySQL (for the obvious reasons), you might want to think about migrating your installation to postgresql. Still your choice, I just don't think you should enforce your need on the rest. :x

**Comment by pschichtel** [comment]
Is there a reasonably automated migration path from MySQL to PG ? I'd be happy to migrate

**Comment by monotek** [comment]
As far as i know not :(

Workaround could be to mount a changed entrypointfile which  supports mysql.
Could maybe done via docker-compose.override.yaml.

**Comment by Syntax3rror404** [comment]
I also doesn't need Elasticsearch, it needs in a small environment lot's of ram! I would love a solution that adds this feature!

**Pull request closed without merging**
