### PR TITLE
Move .env file to .env.dist to avoid update conflicts.

### PR DESCRIPTION
**Pull request by mgruner**
Now that the `.env` file is only needed if any customizations should be done over the default values, we should move it to `.env.dist` to ensure that users can safely update from git or via download, copying the new files over.

### CODE REVIEW

**Comment by mgruner** [comment]
@ralf401 FYI

**Comment by monotek** [comment]
Not sure if this will work for users already using a changed/cusom env file which would be gone afterwards?
Have you tested it?

**Comment by mgruner** [comment]
@monotek you mean when they perform a `git pull`, that the local changes would be lost? Git prevents this:

```
error: Your local changes to the following files would be overwritten by checkout:
        .env
Please commit your changes or stash them before you switch branches.
Aborting
```

Also when they update by downloading the archive and copying over there should be no issue, as the `.env` file is not deleted.

This is in fact the driver of the current PR, because git update will not work if you have local changes in a file that is controlled by git. So it's better to copy the file to a local, untracked version and modify that one.

**Comment by mgruner** [comment]
@monotek just also added `.env` and `docker-compose.override.yml` to `.gitignore` so that it will not complain about adding them to the worktree, if they exist.

**Review by monotek — APPROVED** [review]

**Pull request merged**
