### PR TITLE
Volumes update to have the date in your local filesystem

### PR DESCRIPTION
**Pull request by teawithfruit**
To create the directories you can use this command:

```
mkdir -p ./data/{data,backup,postgresql,elasticsearch}
```

### CODE REVIEW

**Comment by monotek** [comment]
whats the upgradepath for users?

**Comment by teawithfruit** [comment]
I do not exactly understand what you mean. Can you clarify your question a bit more?

**Comment by monotek** [comment]
If you change the directories, they will be empty after an update.
So it will not work for an user which is already running the current version.

**Comment by teawithfruit** [comment]
That's probably right. But in fact that this repo do not serves the stable version of zammad, the users maybe can be informed about that change in the readme.
But if you have an idea to perform that change, you can give me a hint.

**Comment by monotek** [comment]
>  But in fact that this repo do not serves the stable version of zammad, 
Thats wrong! It does use zammad stable branch.
See: https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/Dockerfile#L8

I also don't see the benefit changing this breaking it for everyone else.

**Pull request closed without merging**
